server:
  port: 7666
  log-level: INFO

chat:
  openai:
    api-key: # 查看地址 https://beta.openai.com/account/api-keys
    max-req-length: 1024 # 限制上下文最大请求文本长度
    max-resp-tokens: 512 # 限制返回的tokens数量
    model-select: # 可选模型默认第一个 参考https://beta.openai.com/docs/models/gpt-3
      - text-davinci-003
      - text-curie-001
      - text-babbage-001
      - text-ada-001
    proxy: # 设置代理
  openai-chatgpt:
    api-key:
    max-req-length: 1536
    max-resp-tokens: 512
    model-select:
      - gpt-3.5-turbo
      - gpt-3.5-turbo-0301
    proxy:

qq:
  # CQ-http地址
  cq-http-url: http://127.0.0.1:8700
  # qq号
  uid:
  # 昵称
  nickname:
wx:
  # 昵称
  nickname:

image:
  # 提示词前缀
  prefix-prompt: masterpiece,best quality,ultra detailed
  # 默认负提示
  default-neg-prompt: three arms,three hands,{lowres}, {{{{{{{{{{{blurry}}}}}}}}}}}, {{{{{{{{{bad hands}}}}}}}}},
    {{{{{missing fingers}}}},(((missing hands))),((missing arms)),bad hands,{{{{{{{{{{{{{extra digit}}}}}}}}}}}}},
    fewer digits,small hands,((three arms)),error, multiple limbs,bad feet,cropped,worst quality,low quality,jpeg artifacts,
    bad anatomy,long nails,{{{{interlocked fingers}}}},((three hands)),milf,ugly,duplicate,morbid,mutilated,tranny,trans,
    trannsexual,mutation,deformed,long neck,bad anatomy,bad proportions,extra arms,extra legs, disfigured,malformed,mutated,
    hermaphrodite,out of frame,extra limbs,missing arms,missing legs,poorly drawn hands,poorty drawn face,mutation,poorly drawn,
    long body,cloned face,mutated hands,bad hands,bad feet,long neck,missing limb,malformed limbs,malformed hands,fused fingers,
    too many fingers,extra fingers,missing fingers,extra digit,fewer digits,mutated hands and fingers,lowres,text,error,cropped,jpeg
  diffusion:
    # 地址
    uri: http://127.0.0.1:7860
    # 图片最大宽度 px
    image-max-width: 1280
    # 图片最大高度 px
    image-max-height: 1280
    # 采样方法
    sampler-index: Euler a
    # 引导规模
    cfg-scale: 7
    # 生成步数
    steps: 22
    # 面部修复
    restore-faces: true
    # extensions 扩展参数,注意顺序不要更改
    script-args:
      - 0
      - 0.9  # 美学优化权重
      - 10 # 美学优化步数
      - 0.0001 # 美学优化学习率
      - false # 球面线性插值
      - aivazovsky # 美学embedding 模型，不设置则不会启动美学优化
      - # 美学描述
      - 0.1 # 球面线性角度
      - false # 美学描述为负提示
  diffusers: # 如果使用release下载的可执行文件运行则不支持
    # 从抱脸下载之后的模型在 user/.cache/huggingface/diffusers 你可以移动到项目目录下，这里改为本地路径 ./xxx
    model-id: CompVis/stable-diffusion-v1-4
    #      model-id: ./CompVis-stable-diffusion-v1-4/
    #      model-id: nuigurumi/basil_mix
    #      model-id: hakurei/waifu-diffusion
    # 是否支持图片参数
    i2i-support: true
    # 图片最大宽度 px
    image-max-width: 824
    # 图片最大高度 px
    image-max-height: 824
    # 引导规模
    guidance: 7.5
    # 步数
    steps: 22

cos: # 使用绘画功能必须配置否则收不到图像
  # 腾讯云cos 参考 https://console.cloud.tencent.com/cos
  tx:
    secret-id:
    secret-key:
    region:
    bucket:

fanyi:
  youdao: # 有道智云 https://ai.youdao.com/console/
    app-key:
    app-secret:

journal:
  mongo:
    uri:
    db:
