server:
  port: 7666
  log-level: INFO

chat:
  default: deepseek
  openai:
    gpt:
      api-key:
      model-select:
        gpt-4o-mini:
          max-tokens: 8192
          max-resp-tokens: 512
        gpt-4o:
          max-tokens: 8192
          max-resp-tokens: 512
      proxy: http://127.0.0.1:7890
      default-system:
  anthropic:
    claude:
      api-key:
      model-select:
        claude-3-opus-20240229:
          max-tokens: 8192
          max-resp-tokens: 512
        claude-3-sonnet-20240229:
          max-tokens: 12384
          max-resp-tokens: 512
        claude-3-5-sonnet-20241022:
          max-tokens: 12384
          max-resp-tokens: 512
        claude-3-haiku:
          max-tokens: 8192
          max-resp-tokens: 512
      proxy: http://127.0.0.1:7890
      default-system:
  iflytek:
    spark: # 星火大模型
      app-id:
      api-key:
      api-secret:
      model-select:
        sparkv3:
          domain: generalv3
          spark-url: ws://spark-api.xf-yun.com/v3.1/chat
          max-length: 8000
        sparkv3.5:
          domain: generalv3.5
          spark-url: ws://spark-api.xf-yun.com/v3.5/chat
          max-length: 8000
  thudm:
    glm:
      model-id: THUDM/chatglm3-6b # or local path
      quantize: 4 # 量化
      max-length: 10240
      top-p: 0.7
      temperature: 0.95
  yi:
    yi-6b-chat:
      model-id: 01-ai/Yi-6b-Chat
      max-tokens: 4096
      max-resp-tokens: 512
  deepseek:
    api:
      api-key:
      model-select:
        deepseek-chat:
          max-tokens: 8192
          max-resp-tokens: 512
        deepseek-reasoner:
          max-tokens: 8192
          max-resp-tokens: 512
      default-system:
    local:
      model-id: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      max-tokens: 4096
      max-resp-tokens: 512
      default-system:

qq:
  # CQ-http地址
  cq-http-url: http://127.0.0.1:5700
  uid:  # qq号
  nickname:  # 昵称
  group-session: true # 群聊时使用相同会话上下文
  group-speech-reply: true # 回复群语音
  private-white-list: # 私聊白名单，不配置则不限制

wx:
  # 昵称
  nickname:

image:
  # 提示词前缀
  prefix-prompt: masterpiece,best quality,ultra detailed
  # 默认负提示
  default-neg-prompt: three arms,three hands,{lowres}, {{{{{{{{{{{blurry}}}}}}}}}}}, {{{{{{{{{bad hands}}}}}}}}},
    {{{{{missing fingers}}}},(((missing hands))),((missing arms)),bad hands,{{{{{{{{{{{{{extra digit}}}}}}}}}}}}},
    fewer digits,small hands,((three arms)),error, multiple limbs,bad feet,cropped,worst quality,low quality,jpeg artifacts,
    bad anatomy,long nails,{{{{interlocked fingers}}}},((three hands)),milf,ugly,duplicate,morbid,mutilated,tranny,trans,
    trannsexual,mutation,deformed,long neck,bad anatomy,bad proportions,extra arms,extra legs, disfigured,malformed,mutated,
    hermaphrodite,out of frame,extra limbs,missing arms,missing legs,poorly drawn hands,poorty drawn face,mutation,poorly drawn,
    long body,cloned face,mutated hands,bad hands,bad feet,long neck,missing limb,malformed limbs,malformed hands,fused fingers,
    too many fingers,extra fingers,missing fingers,extra digit,fewer digits,mutated hands and fingers,lowres,text,error,cropped,jpeg
  reply-template: "提示:{prompt}\n负提示:{neg_prompt}\n随机数:{seed}\n时间:{elapsed_sec:.2f}秒\n宽高:{size}\n{image}"
  diffusion:
    # sd接口地址
    uri: http://127.0.0.1:7860
    proxy:
    # 图片最大宽度 px
    image-max-width: 1280
    # 图片最大高度 px
    image-max-height: 1280
    # 采样方法
    sampler-index: Euler a
    # 引导规模
    cfg-scale: 7
    # 生成步数
    steps: 22
    # 面部修复
    restore-faces: true
    # extensions 扩展参数
    script-args:
  diffusers: # 如果使用release下载的可执行文件运行则不支持
    # 从抱脸下载之后的模型在 user/.cache/huggingface/diffusers 你可以移动到项目目录下，这里改为本地路径 ./xxx
    model-id: CompVis/stable-diffusion-v1-4
    #      model-id: ./CompVis-stable-diffusion-v1-4/
    #      model-id: nuigurumi/basil_mix
    #      model-id: hakurei/waifu-diffusion
    # 是否支持图片参数
    i2i-support: true
    # 图片最大宽度 px
    image-max-width: 824
    # 图片最大高度 px
    image-max-height: 824
    # 引导规模
    guidance: 7.5
    # 步数
    steps: 22

cos: # 使用绘画/语音功能必须配置否则收不到图像/音频
  # 腾讯云cos 参考 https://console.cloud.tencent.com/cos
  tx:
    secret-id:
    secret-key:
    region:
    bucket:
    store-dir: "{type}/{date}"

fanyi: # 若不需要绘画prompt翻译请忽略
  youdao: # 有道智云 https://ai.youdao.com/console/
    app-key:
    app-secret:

plugin:
  tts: # 若不需要文本转语音请忽略
    aliyun:
      app-key:
      access-key-id:
      access-key-secret:
  image-recog:
    aliyun:
      access-key-id:
      access-key-secret:
  speech-recog:
    voices-base-path: ./audio/
    aliyun:
      app-key:
      access-key-id:
      access-key-secret:

journal: # 若不需要记录请忽略
  mongo:
    uri: #mongodb://admin:123456@127.0.0.1:27017/
    db: #aichat
