server:
  port: 7666
  log-level: INFO

chat:
  openai:
    gpt:
      api-key: # your api key
      model-select:
        gpt-3.5-turbo:
          max-tokens: 4096
          max-resp-tokens: 768
        gpt-3.5-turbo-0613:
          max-tokens: 4096
          max-resp-tokens: 768
        gpt-3.5-turbo-16k:
          max-tokens: 16384
          max-resp-tokens: 768
        gpt-3.5-turbo-16k-0613:
          max-tokens: 16384
          max-resp-tokens: 768
        gpt-4:
          max-tokens: 8192
          max-resp-tokens: 768
        gpt-4-0613:
          max-tokens: 8192
          max-resp-tokens: 768
        gpt-4-32k:
          max-tokens: 32768
          max-resp-tokens: 768
        gpt-4-32k-0613:
          max-tokens: 32768
          max-resp-tokens: 768
      proxy: http://127.0.0.1:7890
      default-system:
  iflytek:
    spark:
      app-id: # your app id
      api-key: # your api key
      api-secret: # your api secret
      model-select:
        sparkv1.5:
          domain: general
          spark-url: ws://spark-api.xf-yun.com/v1.1/chat
          max-length: 8000
        sparkv2:
          domain: generalv2
          spark-url: ws://spark-api.xf-yun.com/v2.1/chat
          max-length: 8000
  thudm:
    glm:
      model-id: THUDM/chatglm2-6b-int4 # or local path
      quantize: 0
      max-length: 2048
      top-p: 0.7
      temperature: 0.95

qq:
  # CQ-http地址
  cq-http-url: http://127.0.0.1:8700
  # qq号
  uid:
  # 昵称
  nickname:
  # 群聊时使用相同会话上下文
  group-session: true
wx:
  # 昵称
  nickname:

image:
  # 提示词前缀
  prefix-prompt: masterpiece,best quality,ultra detailed
  # 默认负提示
  default-neg-prompt: three arms,three hands,{lowres}, {{{{{{{{{{{blurry}}}}}}}}}}}, {{{{{{{{{bad hands}}}}}}}}},
    {{{{{missing fingers}}}},(((missing hands))),((missing arms)),bad hands,{{{{{{{{{{{{{extra digit}}}}}}}}}}}}},
    fewer digits,small hands,((three arms)),error, multiple limbs,bad feet,cropped,worst quality,low quality,jpeg artifacts,
    bad anatomy,long nails,{{{{interlocked fingers}}}},((three hands)),milf,ugly,duplicate,morbid,mutilated,tranny,trans,
    trannsexual,mutation,deformed,long neck,bad anatomy,bad proportions,extra arms,extra legs, disfigured,malformed,mutated,
    hermaphrodite,out of frame,extra limbs,missing arms,missing legs,poorly drawn hands,poorty drawn face,mutation,poorly drawn,
    long body,cloned face,mutated hands,bad hands,bad feet,long neck,missing limb,malformed limbs,malformed hands,fused fingers,
    too many fingers,extra fingers,missing fingers,extra digit,fewer digits,mutated hands and fingers,lowres,text,error,cropped,jpeg
  reply-template: "提示:{prompt}\n负提示:{neg_prompt}\n随机数:{seed}\n时间:{elapsed_sec:.2f}秒\n宽高:{size}\n{image}"
  diffusion:
    # sd接口地址
    uri: http://127.0.0.1:7860
    proxy:
    # 图片最大宽度 px
    image-max-width: 1280
    # 图片最大高度 px
    image-max-height: 1280
    # 采样方法
    sampler-index: Euler a
    # 引导规模
    cfg-scale: 7
    # 生成步数
    steps: 22
    # 面部修复
    restore-faces: true
    # extensions 扩展参数
    script-args:
  diffusers: # 如果使用release下载的可执行文件运行则不支持
    # 从抱脸下载之后的模型在 user/.cache/huggingface/diffusers 你可以移动到项目目录下，这里改为本地路径 ./xxx
    model-id: CompVis/stable-diffusion-v1-4
    #      model-id: ./CompVis-stable-diffusion-v1-4/
    #      model-id: nuigurumi/basil_mix
    #      model-id: hakurei/waifu-diffusion
    # 是否支持图片参数
    i2i-support: true
    # 图片最大宽度 px
    image-max-width: 824
    # 图片最大高度 px
    image-max-height: 824
    # 引导规模
    guidance: 7.5
    # 步数
    steps: 22

cos: # 使用绘画功能必须配置否则收不到图像
  # 腾讯云cos 参考 https://console.cloud.tencent.com/cos
  tx:
    secret-id:
    secret-key:
    region:
    bucket:

fanyi: # 若不需要绘画prompt翻译请忽略
  youdao: # 有道智云 https://ai.youdao.com/console/
    app-key:
    app-secret:

plugin:
  tts: # 若不需要文本转语音请忽略
    aliyun:
      app-key:
      access-key-id:
      access-key-secret:
  image-recog:
    aliyun:
      access-key-id:
      access-key-secret:

journal: # 若不需要记录请忽略
  mongo:
    uri:
    db:
