name: build_for_linux

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_api.txt
    - name: build
      run: |
        pip install pyinstaller
        pyinstaller -F main.py
        mv ./dist/main ./dist/aichat_linux_amd64
    - name: Add config_example.yaml to dist
      run: cp config_example.yaml ./dist/
    - name: Upload artifacts linux_amd64
      uses: actions/upload-artifact@v3
      with:
        name: linux_amd64
        path: ./dist
